import { FastifyInstance } from 'fastify';
import { ok } from '../../shared/response';
import { authenticate } from '../../shared/middleware/authenticate';

export default async function diagnosisRoutes(app: FastifyInstance) {
  const auth = { preHandler: authenticate };

  // GET /api/v1/diagnosis/:attemptId — full breakdown for one attempt
  app.get('/:attemptId', auth, async (request, reply) => {
    const { attemptId } = request.params as { attemptId: string };
    // TODO: DiagnosisService.getFullDiagnosis(attemptId, request.user.id)
    return reply.status(200).send(ok({ attemptId, mistakeDna: [], strategyScore: null }));
  });

  // GET /api/v1/diagnosis/history — past diagnosis summaries (trend view)
  app.get('/history', auth, async (request, reply) => {
    // TODO: DiagnosisService.getHistory(request.user.id, query.page)
    return reply.status(200).send(ok({ history: [] }));
  });

  // GET /api/v1/diagnosis/aaj-ka-kaam — today's one-task recommendation
  // Cached in Redis for 24h per student (generated by AI job after diagnosis)
  app.get('/aaj-ka-kaam', auth, async (request, reply) => {
    // TODO: DiagnosisService.getAajKaKaam(request.user.id)
    return reply.status(200).send(ok({ task: null, generatedAt: null }));
  });
}
